--person
SELECT 
   '#PERSON_SEQ#' AS PERSON_ID,
   '#Lookup to PARTY.PARTY_ID using BUS_CODE=PARTY.BUS_CODE AND PARTY.SOURCE_SYS_CD=OPIL#' AS PARTY_ID,
   CASE WHEN CP.MIDDLE_NAME IS NULL THEN TRIM (CP.FIRST_NAME)||' '||TRIM (CPE.LAST_NAME) ELSE TRIM (CP.FIRST_NAME) || ' ' || CP.MIDDLE_NAME || ' ' || TRIM (CPE.LAST_NAME) END AS LONG_NAME,
   CP.FIRST_NAME AS FIRST_NAME,
   CP.MIDDLE_NAME AS MIDDLE_NAME,
   CPE.LAST_NAME AS LAST_NAME,
   CP.AFTER_TITLE AS AFTER_TITLE,
   CP.BEFORE_TITLE AS BEFORE_TITLE,
   CASE WHEN CP.SEX='M' THEN 'MALE' ELSE 'FEMALE' END AS GENDER_CD,
   CASE CP.MARITAL_STATUS WHEN 'M' THEN 'MARRIED' WHEN 'S' THEN 'SINGLE' WHEN 'D' THEN 'DIVORCE' END AS MARITAL_STS_CD,
   NAT.SCREEN_VALUE AS NATIONALITY_CD,
   CP.DATE_OF_BIRTH AS DOB,
   CPE.RELIGION AS RELIGION_CD,
   CPE.BIRTH_PLACE AS BIRTH_PLACE,
   TO_CHAR(CP.PART_ID) AS BUS_CODE,
   'OPIL' AS SOURCE_SYS_CD,
   '#Type_II_SCD#' AS START_DATE,
   '#Type_II_SCD#' AS END_DATE,
   '#ETL_JOB_NAME#' AS CREATE_BY,
   SYSDATE AS CREATE_DATE,
   '#Type_II_SCD#' AS UPD_BY,
   '#Type_II_SCD#' AS UPD_DATE
FROM CP_PARTNERS CP
INNER JOIN AZLI_CPT_PARTNER_EXTS CPE ON CP.PART_ID=CPE.PART_ID
LEFT JOIN INF_DNM_POPLISTS NAT ON CP.NATIONALITY=NAT.INTERNAL_VALUE AND NAT.POPLIST_CODE='NATIONALITY' AND NAT.LANGUAGE='US' 
WHERE CP.PARTNER_TYPE='P';



--check issue ledwh-270
SELECT CP.PART_ID,
CASE
WHEN CP.MIDDLE_NAME IS NULL THEN
  TRIM (CP.FIRST_NAME)||' '||TRIM (CPE.LAST_NAME)
ELSE 
  TRIM (CP.FIRST_NAME)||' '|| CP.MIDDLE_NAME ||' '|| TRIM (CPE.LAST_NAME)
END
AS
  LONG_NAME
FROM CP_PARTNERS CP
INNER JOIN AZLI_CPT_PARTNER_EXTS CPE ON CP.PART_ID=CPE.PART_ID
LEFT JOIN INF_DNM_POPLISTS NAT ON CP.NATIONALITY=NAT.INTERNAL_VALUE AND NAT.POPLIST_CODE='NATIONALITY' AND NAT.LANGUAGE='US'
WHERE CP.PARTNER_TYPE='P';


--person-detail
SELECT 
   '#PERSON_DETAIL_SEQ#' AS PERSON_DTL_ID,
   '#Lookup to PARTY.PARTY_ID using BUS_CODE=PARTY.BUS_CODE AND PARTY.SOURCE_SYS_CD=OPIL#' AS PARTY_ID,
   OCC.SCREEN_VALUE AS OCCUP_CD,
   CPE.HEIGHT AS HEIGHT,
   CPE.WEIGHT AS WEIGHT,
   CASE CPE.SMOKER WHEN 'S' THEN 'SMOKER' ELSE 'NON-SMOKER' END AS SMOKER_FLAG,
   TO_CHAR(CP.PART_ID) AS BUS_CODE,
   'OPIL' AS SOURCE_SYS_CD,
   '#Type_II_SCD#' AS START_DATE,
   '#Type_II_SCD#' AS END_DATE,
   '#ETL_JOB_NAME#' AS CREATE_BY,
   SYSDATE AS CREATE_DATE,
   '#Type_II_SCD#' AS UPD_BY,
   '#Type_II_SCD#' AS UPD_DATE
FROM CP_PARTNERS CP
INNER JOIN AZLI_CPT_PARTNER_EXTS CPE ON CP.PART_ID=CPE.PART_ID
LEFT JOIN INF_DNM_POPLISTS OCC ON CP.OCCUPATION=OCC.INTERNAL_VALUE AND OCC.POPLIST_CODE='OCCUPATION' AND OCC.LANGUAGE='US'
WHERE CP.PARTNER_TYPE='P'